#include "common.h"

std::unordered_map<TokenType, std::string> tokens_map = {
    {L_PAREN, "LParen"},
    {R_PAREN, "RParen"},
    {L_BRACE, "LBrace"},
    {R_BRACE, "RBrace"},
    {COMMA, "Comma"},
    {DOT, "Dot"},
    {MINUS, "Minus"},
    {PLUS, "Plus"},
    {SEMICOLON, "Semicolon"},
    {SLASH, "Slash"},
    {STAR, "Star"},
    {BANG, "Bang"},
    {BANG_EQUAL, "BangEqual"},
    {EQUAL, "Equal"},
    {EQUAL_EQUAL, "EqualEqual"},
    {GREATER, "Greater"},
    {GREATER_EQUAL, "GreaterEqual"},
    {LESSER, "Lesser"},
    {LESSER_EQUAL, "LesserEqual"},
    {IDENTIFIER, "Identifier"},
    {STRING, "String"},
    {NUMBER, "Number"},
    {A, "AA"},
    {TRIEDA, "Trieda"},
    {INAK, "Inak"},
    {NEPRAVDA, "Nepravda"},
    {FUNK, "Funk"},
    {PRE, "Pre"},
    {AK, "Ak"},
    {NIC, "Nic"},
    {ALEBO, "Alebo"},
    {VYTLAC, "Vytlac"},
    {VRATIT, "Vratit"},
    {SUPER, "Super"},
    {TOTO, "Toto"},
    {PRAVDA, "Pravda"},
    {LET, "Let"},
    {POKIAL, "Pokial"},
    {_EOF, "Eof"}
};

std::unordered_map<std::string, TokenType> keywords_map = {
    {"aa", A},
    {"trieda", TRIEDA},
    {"inak", INAK},
    {"nepravda", NEPRAVDA},
    {"funk", FUNK},
    {"pre", PRE},
    {"ak", AK},
    {"nic", NIC},
    {"alebo", ALEBO},
    {"vytlac", VYTLAC},
    {"vratit", VRATIT},
    {"super", SUPER},
    {"toto", TOTO},
    {"pravda", PRAVDA},
    {"let", LET},
    {"pokial", POKIAL}
};
